In [4]:
import pandas as pd

In [16]:
mad2018 = pd.read_csv('../output/AUDL2018_MadisonRadicals.csv', index_col=0)
mad2018.head()

,Date/Time,Opponent,Point Elapsed Seconds,Line,Our Score - End of Point,Their Score - End of Point,Event Type,Action,Passer,Receiver,...,Begin Y,End Area,End X,End Y,Distance Unit of Measure,Absolute Distance,Lateral Distance,Toward Our Goal Distance,Teamname,Tournament
0,2018-05-13 12:01,Detroit Mechanix,50,O,1,0,Offense,Catch,RWiseman,A Brown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madison Radicals,AUDL 2018
1,2018-05-13 12:01,Detroit Mechanix,50,O,1,0,Offense,Catch,A Brown,Camp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madison Radicals,AUDL 2018
2,2018-05-13 12:01,Detroit Mechanix,50,O,1,0,Offense,Catch,Camp,A Brown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madison Radicals,AUDL 2018
3,2018-05-13 12:01,Detroit Mechanix,50,O,1,0,Offense,Catch,A Brown,Shriwise,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madison Radicals,AUDL 2018
4,2018-05-13 12:01,Detroit Mechanix,50,O,1,0,Offense,Catch,Shriwise,Camp,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Madison Radicals,AUDL 2018

In [20]:
mad2018.columns

Index(['Date/Time', 'Opponent', 'Point Elapsed Seconds', 'Line',
       'Our Score - End of Point', 'Their Score - End of Point', 'Event Type',
       'Action', 'Passer', 'Receiver', 'Defender', 'Hang Time (secs)',
       'Player 0', 'Player 1', 'Player 2', 'Player 3', 'Player 4', 'Player 5',
       'Player 6', 'Player 7', 'Player 8', 'Player 9', 'Player 10',
       'Player 11', 'Player 12', 'Player 13', 'Player 14', 'Player 15',
       'Player 16', 'Player 17', 'Player 18', 'Player 19', 'Player 20',
       'Player 21', 'Player 22', 'Player 23', 'Player 24', 'Player 25',
       'Player 26', 'Player 27', 'Elapsed Time (secs)', 'Begin Area',
       'Begin X', 'Begin Y', 'End Area', 'End X', 'End Y',
       'Distance Unit of Measure', 'Absolute Distance', 'Lateral Distance',
       'Toward Our Goal Distance', 'Teamname', 'Tournament'],
      dtype='object')

In [18]:
mad2018[mad2018.Action=='GameOver'][['Date/Time','Opponent', 'Our Score - End of Point','Their Score - End of Point']].sort_values('Date/Time')

,Date/Time,Opponent,Our Score - End of Point,Their Score - End of Point
1368,2018-04-07 19:38,Indianapolis AlleyCats,20,13
5929,2018-04-21 17:12,Detroit Mechanix,27,12
3210,2018-04-28 17:58,Pittsburgh Thunderbirds,29,13
5596,2018-05-05 15:25,Minnesota Wind Chill,20,19
318,2018-05-13 12:01,Detroit Mechanix,37,8
2479,2018-05-19 18:00,Chicago Wildfire,24,16
4374,2018-05-26 18:59,Raleigh Flyers,16,24
5302,2018-06-08 18:59,Minnesota Wind Chill,20,17
4006,2018-06-09 19:00,Chicago Wildfire,22,21
680,2018-06-16 17:42,Pittsburgh Thunderbirds,25,21
4975,2018-06-17 16:00,Indianapolis AlleyCats,20,21
2161,2018-06-30 18:02,Indianapolis AlleyCats,26,17
2861,2018-07-03 18:58,Minnesota Wind Chill,35,24
3641,2018-07-14 17:58,Chicago Wildfire,27,24
1736,2018-07-28 17:59,Indianapolis AlleyCats,27,18
1074,2018-08-11 19:05,Los Angeles Aviators,24,19
4641,2018-08-12 12:05,Dallas Roughnecks,20,16